# Generated by Django 2.0 on 2017-12-25 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20171222_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='item.Category'),
        ),
    ]
